################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/STM32U5xx_HAL_Driver/Src \
Drivers/lvgl/env_support/pikascript \
Drivers/lvgl/env_support/rt-thread \
Drivers/lvgl/env_support/rt-thread/squareline \
Drivers/lvgl/src/core \
Drivers/lvgl/src/display \
Drivers/lvgl/src/draw/dma2d \
Drivers/lvgl/src/draw \
Drivers/lvgl/src/draw/nema_gfx \
Drivers/lvgl/src/draw/nxp/g2d \
Drivers/lvgl/src/draw/nxp/pxp \
Drivers/lvgl/src/draw/nxp/vglite \
Drivers/lvgl/src/draw/opengles \
Drivers/lvgl/src/draw/renesas/dave2d \
Drivers/lvgl/src/draw/sdl \
Drivers/lvgl/src/draw/sw/blend/helium \
Drivers/lvgl/src/draw/sw/blend \
Drivers/lvgl/src/draw/sw/blend/neon \
Drivers/lvgl/src/draw/sw \
Drivers/lvgl/src/draw/vg_lite \
Drivers/lvgl/src/drivers/display/drm \
Drivers/lvgl/src/drivers/display/fb \
Drivers/lvgl/src/drivers/display/ft81x \
Drivers/lvgl/src/drivers/display/ili9341 \
Drivers/lvgl/src/drivers/display/lcd \
Drivers/lvgl/src/drivers/display/renesas_glcdc \
Drivers/lvgl/src/drivers/display/st7735 \
Drivers/lvgl/src/drivers/display/st7789 \
Drivers/lvgl/src/drivers/display/st7796 \
Drivers/lvgl/src/drivers/display/st_ltdc \
Drivers/lvgl/src/drivers/evdev \
Drivers/lvgl/src/drivers/glfw \
Drivers/lvgl/src/drivers/libinput \
Drivers/lvgl/src/drivers/nuttx \
Drivers/lvgl/src/drivers/qnx \
Drivers/lvgl/src/drivers/sdl \
Drivers/lvgl/src/drivers/uefi \
Drivers/lvgl/src/drivers/wayland \
Drivers/lvgl/src/drivers/windows \
Drivers/lvgl/src/drivers/x11 \
Drivers/lvgl/src/font \
Drivers/lvgl/src/indev \
Drivers/lvgl/src/layouts/flex \
Drivers/lvgl/src/layouts/grid \
Drivers/lvgl/src/layouts \
Drivers/lvgl/src/libs/barcode \
Drivers/lvgl/src/libs/bin_decoder \
Drivers/lvgl/src/libs/bmp \
Drivers/lvgl/src/libs/expat \
Drivers/lvgl/src/libs/ffmpeg \
Drivers/lvgl/src/libs/freetype \
Drivers/lvgl/src/libs/fsdrv \
Drivers/lvgl/src/libs/gif \
Drivers/lvgl/src/libs/libjpeg_turbo \
Drivers/lvgl/src/libs/libpng \
Drivers/lvgl/src/libs/lodepng \
Drivers/lvgl/src/libs/lz4 \
Drivers/lvgl/src/libs/qrcode \
Drivers/lvgl/src/libs/rle \
Drivers/lvgl/src/libs/rlottie \
Drivers/lvgl/src/libs/svg \
Drivers/lvgl/src/libs/tiny_ttf \
Drivers/lvgl/src/libs/tjpgd \
Drivers/lvgl/src \
Drivers/lvgl/src/misc/cache/class \
Drivers/lvgl/src/misc/cache/instance \
Drivers/lvgl/src/misc/cache \
Drivers/lvgl/src/misc \
Drivers/lvgl/src/osal \
Drivers/lvgl/src/others/file_explorer \
Drivers/lvgl/src/others/font_manager \
Drivers/lvgl/src/others/fragment \
Drivers/lvgl/src/others/gridnav \
Drivers/lvgl/src/others/ime \
Drivers/lvgl/src/others/imgfont \
Drivers/lvgl/src/others/monkey \
Drivers/lvgl/src/others/observer \
Drivers/lvgl/src/others/snapshot \
Drivers/lvgl/src/others/sysmon \
Drivers/lvgl/src/others/test \
Drivers/lvgl/src/others/vg_lite_tvg \
Drivers/lvgl/src/others/xml \
Drivers/lvgl/src/others/xml/parsers \
Drivers/lvgl/src/stdlib/builtin \
Drivers/lvgl/src/stdlib/clib \
Drivers/lvgl/src/stdlib \
Drivers/lvgl/src/stdlib/micropython \
Drivers/lvgl/src/stdlib/rtthread \
Drivers/lvgl/src/stdlib/uefi \
Drivers/lvgl/src/themes/default \
Drivers/lvgl/src/themes \
Drivers/lvgl/src/themes/mono \
Drivers/lvgl/src/themes/simple \
Drivers/lvgl/src/tick \
Drivers/lvgl/src/widgets/3dtexture \
Drivers/lvgl/src/widgets/animimage \
Drivers/lvgl/src/widgets/arc \
Drivers/lvgl/src/widgets/bar \
Drivers/lvgl/src/widgets/button \
Drivers/lvgl/src/widgets/buttonmatrix \
Drivers/lvgl/src/widgets/calendar \
Drivers/lvgl/src/widgets/canvas \
Drivers/lvgl/src/widgets/chart \
Drivers/lvgl/src/widgets/checkbox \
Drivers/lvgl/src/widgets/dropdown \
Drivers/lvgl/src/widgets/image \
Drivers/lvgl/src/widgets/imagebutton \
Drivers/lvgl/src/widgets/keyboard \
Drivers/lvgl/src/widgets/label \
Drivers/lvgl/src/widgets/led \
Drivers/lvgl/src/widgets/line \
Drivers/lvgl/src/widgets/list \
Drivers/lvgl/src/widgets/lottie \
Drivers/lvgl/src/widgets/menu \
Drivers/lvgl/src/widgets/msgbox \
Drivers/lvgl/src/widgets/objx_templ \
Drivers/lvgl/src/widgets/property \
Drivers/lvgl/src/widgets/roller \
Drivers/lvgl/src/widgets/scale \
Drivers/lvgl/src/widgets/slider \
Drivers/lvgl/src/widgets/span \
Drivers/lvgl/src/widgets/spinbox \
Drivers/lvgl/src/widgets/spinner \
Drivers/lvgl/src/widgets/switch \
Drivers/lvgl/src/widgets/table \
Drivers/lvgl/src/widgets/tabview \
Drivers/lvgl/src/widgets/textarea \
Drivers/lvgl/src/widgets/tileview \
Drivers/lvgl/src/widgets/win \

